import Link from "next/link";
import { requireAuthenticatedUser } from "@/lib/auth/require-auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { completeMakeup, createMakeupRequest, scheduleMakeup } from "./actions";

const GROUP_LABELS: Record<string,string> = { requested: "보강 대기", scheduled: "보강 예정", completed: "완료" };
export default async function MakeupPage({ searchParams }: { searchParams: Promise<{ error?: string; updated?: string }> }) {
  await requireAuthenticatedUser("/login/operator", "operator");
  const notices = await searchParams; const supabase = await createSupabaseServerClient();
  const [{ data: makeups }, { data: students }, { data: lessons }] = await Promise.all([supabase.from("makeup_lessons").select("id, student_id, original_lesson_id, replacement_lesson_id, reason, status, created_at").order("created_at"), supabase.from("students").select("id, nickname").order("nickname"), supabase.from("lessons").select("id, title, starts_at, program_type, status").neq("status", "cancelled").order("starts_at")]);
  const name = (id:string) => students?.find((student) => student.id === id)?.nickname ?? "학생"; const title = (id:string|null) => lessons?.find((lesson) => lesson.id === id)?.title ?? "일정";
  return <main className="mx-auto w-full max-w-5xl px-5 py-10"><h1 className="text-3xl font-bold">보강관리</h1>{notices.error ? <p className="mt-4 rounded-xl bg-rose-50 p-4 font-bold text-rose-900">보강 정보를 처리하지 못했습니다. 중복 요청·프로그램·출결·시간 충돌을 확인해 주세요.</p> : null}<form action={createMakeupRequest} className="mt-6 grid gap-3 rounded-2xl border bg-white p-5 sm:grid-cols-3"><select name="student_id" required className="h-11 rounded-xl border px-3">{students?.map((student) => <option key={student.id} value={student.id}>{student.nickname}</option>)}</select><select name="original_lesson_id" required className="h-11 rounded-xl border px-3">{lessons?.map((lesson) => <option key={lesson.id} value={lesson.id}>{lesson.title}</option>)}</select><input name="reason" placeholder="보강 사유" className="h-11 rounded-xl border px-3"/><button className="h-11 rounded-xl bg-[var(--accent)] font-bold text-white sm:col-span-3">보강 대기 등록</button></form><div className="mt-8 grid gap-5 lg:grid-cols-3">{Object.keys(GROUP_LABELS).map((status) => <section key={status}><h2 className="text-xl font-bold">{GROUP_LABELS[status]}</h2><ul className="mt-3 space-y-3">{(makeups ?? []).filter((item) => item.status === status).map((item) => <li key={item.id} className="rounded-xl border bg-white p-4"><p className="font-bold">{name(item.student_id)}</p><p className="mt-1 text-sm">원수업: {title(item.original_lesson_id)}</p><p className="mt-1 text-sm text-[var(--muted)]">{item.reason || "사유 없음"}</p>{status === "requested" ? <form action={scheduleMakeup.bind(null,item.id)} className="mt-3 space-y-2"><select name="replacement_lesson_id" required className="h-10 w-full rounded-lg border px-2">{lessons?.filter((lesson) => lesson.id !== item.original_lesson_id).map((lesson) => <option key={lesson.id} value={lesson.id}>{lesson.title}</option>)}</select><button className="h-10 w-full rounded-lg border font-bold">일정 배정</button><Link href="/operator/schedules/new" className="block text-center text-sm font-bold underline">새 일정 생성</Link></form> : status === "scheduled" ? <form action={completeMakeup.bind(null,item.id)} className="mt-3"><p className="text-sm">대체: {title(item.replacement_lesson_id)}</p><button className="mt-2 h-10 w-full rounded-lg border font-bold">출결 확인 후 완료</button></form> : null}</li>)}</ul></section>)}</div></main>;
}
